
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sib.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 6;
  public static final int IMPORT = 4;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 5;
  public static final int PALABRA_RESERVADA = 2;
  public static final int PACKAGE = 3;
  public static final int PUNTO_Y_COMA = 7;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PALABRA_RESERVADA",
  "PACKAGE",
  "IMPORT",
  "IDENTIFICADOR",
  "PUNTO",
  "PUNTO_Y_COMA"
  };
}

