
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sib.cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMPARADOR = 34;
  public static final int READPARTITURE = 22;
  public static final int MULT = 29;
  public static final int TIPO = 7;
  public static final int PUNTO_Y_COMA = 8;
  public static final int NUMERO_INT_FRAC = 25;
  public static final int LPAREN = 16;
  public static final int RPAREN = 17;
  public static final int IDENTIFICADOR = 3;
  public static final int DIV = 28;
  public static final int BEGIN = 2;
  public static final int IF = 31;
  public static final int ENDWHILE = 36;
  public static final int EOF = 0;
  public static final int PROPIEDAD = 6;
  public static final int IGUAL_SIMPLE = 10;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int CADENA = 15;
  public static final int NUMERO_REAL = 24;
  public static final int MENOS = 27;
  public static final int MOD = 30;
  public static final int ENDIF = 32;
  public static final int ELSE = 33;
  public static final int VARIABLE = 5;
  public static final int READ = 21;
  public static final int WHILE = 35;
  public static final int CLEF_VALUE = 13;
  public static final int PLAYPARTITURE = 20;
  public static final int ACCENT_VALUE = 14;
  public static final int TRANS = 18;
  public static final int END = 4;
  public static final int PLAY = 19;
  public static final int OPERADOR_NOTA = 11;
  public static final int NUMERO_ENTERO = 23;
  public static final int STEP = 12;
  public static final int MAS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "IDENTIFICADOR",
  "END",
  "VARIABLE",
  "PROPIEDAD",
  "TIPO",
  "PUNTO_Y_COMA",
  "COMA",
  "IGUAL_SIMPLE",
  "OPERADOR_NOTA",
  "STEP",
  "CLEF_VALUE",
  "ACCENT_VALUE",
  "CADENA",
  "LPAREN",
  "RPAREN",
  "TRANS",
  "PLAY",
  "PLAYPARTITURE",
  "READ",
  "READPARTITURE",
  "NUMERO_ENTERO",
  "NUMERO_REAL",
  "NUMERO_INT_FRAC",
  "MAS",
  "MENOS",
  "DIV",
  "MULT",
  "MOD",
  "IF",
  "ENDIF",
  "ELSE",
  "COMPARADOR",
  "WHILE",
  "ENDWHILE"
  };
}

