/* The following code was generated by JFlex 1.6.1 */

/* Sección de declaraciones de JFlex */
package sib.flex;

import sib.cup.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/sib/flex/AnalizadorLexicoFase2.flex</tt>
 */
public class AnalizadorLexicoFase2 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CADENA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\74\1\72\1\76\1\74\1\73\22\0\1\74\1\55\1\56"+
    "\1\53\1\62\1\57\1\0\1\55\1\51\1\52\1\57\1\57\1\46"+
    "\1\60\1\45\1\61\1\70\1\66\1\64\2\65\5\70\1\0\1\47"+
    "\1\55\1\50\1\55\1\0\1\54\1\13\1\23\1\14\1\5\1\3"+
    "\1\2\1\16\1\11\1\1\1\71\1\15\1\6\1\17\1\4\1\20"+
    "\1\12\1\71\1\21\1\7\1\22\2\71\1\10\3\71\1\55\1\75"+
    "\1\55\1\0\1\63\1\0\1\32\1\41\1\34\1\71\1\37\1\27"+
    "\1\36\1\71\1\24\1\42\1\71\1\30\1\67\1\25\1\31\1\40"+
    "\1\71\1\33\1\35\1\26\1\44\3\71\1\43\1\71\1\55\1\0"+
    "\1\55\7\0\1\76\u1fa2\0\1\76\1\76\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\2\2\3\2\2\3\3"+
    "\11\2\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\4\1\13\2\14\2\1\1\15\1\2\2\16\1\17"+
    "\1\20\1\21\1\1\1\22\1\2\3\3\1\23\7\2"+
    "\1\24\12\2\1\0\1\25\4\26\3\0\1\2\1\27"+
    "\1\2\1\30\4\2\1\31\15\2\1\0\1\26\1\32"+
    "\1\0\1\33\20\2\1\34\1\35\5\2\1\36\1\2"+
    "\1\24\2\2\1\37\6\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\176\0\275\0\374\0\u013b\0\u017a\0\u01b9"+
    "\0\u017a\0\u01f8\0\u0237\0\u0276\0\u02b5\0\u02f4\0\u0333\0\u0372"+
    "\0\u03b1\0\u03f0\0\u042f\0\u046e\0\u04ad\0\u04ec\0\u052b\0\u017a"+
    "\0\176\0\176\0\176\0\176\0\176\0\176\0\176\0\176"+
    "\0\176\0\u056a\0\u05a9\0\u05e8\0\u0627\0\u0666\0\176\0\u06a5"+
    "\0\176\0\176\0\176\0\u06e4\0\u017a\0\u0723\0\u0762\0\u07a1"+
    "\0\176\0\176\0\u07e0\0\u081f\0\u085e\0\u089d\0\u08dc\0\u091b"+
    "\0\u095a\0\u0999\0\u09d8\0\u0a17\0\u0a56\0\u0a95\0\u0ad4\0\u0b13"+
    "\0\u0b52\0\u0b91\0\u0bd0\0\u0c0f\0\u0c4e\0\u05a9\0\u0c8d\0\u0ccc"+
    "\0\u0d0b\0\176\0\u0d4a\0\u0d89\0\u0dc8\0\u0e07\0\176\0\u0e46"+
    "\0\u0e85\0\u0ec4\0\u0f03\0\u0f42\0\u0f81\0\u017a\0\u0fc0\0\u0fff"+
    "\0\u103e\0\u107d\0\u10bc\0\u10fb\0\u113a\0\u1179\0\u11b8\0\u11f7"+
    "\0\u1236\0\u1275\0\u12b4\0\u12f3\0\u1332\0\u0d4a\0\u1371\0\u1371"+
    "\0\u13b0\0\u13ef\0\u142e\0\u146d\0\u14ac\0\u14eb\0\u152a\0\u1569"+
    "\0\u15a8\0\u15e7\0\u1626\0\u1665\0\u16a4\0\u16e3\0\u1722\0\u1761"+
    "\0\u017a\0\u017a\0\u17a0\0\u17df\0\u181e\0\u185d\0\u189c\0\u017a"+
    "\0\u18db\0\u017a\0\u191a\0\u1959\0\u017a\0\u1998\0\u19d7\0\u1a16"+
    "\0\u1a55\0\u1a94\0\u1ad3";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\7\1\11"+
    "\1\12\1\7\1\13\1\10\1\14\1\7\1\15\4\7"+
    "\1\16\1\17\1\20\1\21\1\22\1\7\1\23\1\24"+
    "\1\7\1\25\1\26\2\7\1\27\1\30\3\7\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\3\37\1\40\1\41"+
    "\1\42\1\41\1\43\1\44\3\45\1\46\1\45\1\7"+
    "\1\47\1\50\1\51\1\3\1\0\56\52\1\53\13\52"+
    "\1\47\1\50\1\52\1\54\1\52\100\0\1\7\1\55"+
    "\14\7\1\56\25\7\22\0\1\7\1\0\1\7\6\0"+
    "\40\7\1\57\3\7\6\0\1\60\1\61\10\0\1\62"+
    "\1\0\1\7\1\0\1\7\6\0\3\7\1\63\1\7"+
    "\1\64\32\7\1\57\3\7\6\0\1\60\1\61\12\0"+
    "\1\7\1\0\1\7\6\0\44\7\22\0\1\7\1\0"+
    "\1\7\6\0\40\7\1\57\3\7\6\0\1\60\1\61"+
    "\12\0\1\7\1\0\1\7\6\0\10\7\1\65\33\7"+
    "\22\0\1\7\1\0\1\7\6\0\12\7\1\66\31\7"+
    "\22\0\1\7\1\0\1\7\6\0\40\7\1\57\3\7"+
    "\6\0\1\60\1\61\7\0\3\62\1\7\1\0\1\7"+
    "\6\0\40\7\1\57\3\7\6\0\1\60\1\61\7\0"+
    "\1\62\2\0\1\7\1\0\1\7\6\0\2\7\1\67"+
    "\35\7\1\57\3\7\6\0\1\60\1\61\12\0\1\7"+
    "\1\0\1\7\6\0\24\7\1\70\17\7\22\0\1\7"+
    "\1\0\1\7\6\0\26\7\1\71\1\7\1\72\13\7"+
    "\22\0\1\7\1\0\1\7\6\0\32\7\1\73\3\7"+
    "\1\74\5\7\22\0\1\7\1\0\1\7\6\0\27\7"+
    "\1\75\2\7\1\76\11\7\22\0\1\7\1\0\1\7"+
    "\6\0\40\7\1\77\3\7\22\0\1\7\1\0\1\7"+
    "\6\0\32\7\1\100\1\101\10\7\22\0\1\7\1\0"+
    "\1\7\6\0\27\7\1\102\14\7\22\0\1\7\1\0"+
    "\1\7\6\0\25\7\1\103\16\7\22\0\1\7\1\0"+
    "\1\7\6\0\31\7\1\104\12\7\22\0\1\7\1\0"+
    "\1\7\65\0\1\105\3\0\3\45\1\0\1\45\7\0"+
    "\44\106\22\0\1\106\1\0\1\106\46\0\1\107\3\0"+
    "\1\110\5\0\1\111\1\112\67\0\1\113\13\0\1\114"+
    "\2\0\3\45\1\0\1\45\3\0\1\115\3\0\31\7"+
    "\1\116\12\7\22\0\1\7\1\0\1\7\77\0\1\47"+
    "\62\0\1\117\21\0\11\7\1\120\32\7\22\0\1\7"+
    "\1\0\1\7\6\0\40\7\1\57\3\7\6\0\1\60"+
    "\13\0\1\7\1\0\1\7\46\0\1\60\11\0\1\60"+
    "\24\0\4\7\1\121\37\7\22\0\1\7\1\0\1\7"+
    "\6\0\6\7\1\122\35\7\22\0\1\7\1\0\1\7"+
    "\6\0\1\123\43\7\22\0\1\7\1\0\1\7\6\0"+
    "\13\7\1\124\30\7\22\0\1\7\1\0\1\7\6\0"+
    "\15\7\1\125\26\7\22\0\1\7\1\0\1\7\6\0"+
    "\25\7\1\126\16\7\22\0\1\7\1\0\1\7\6\0"+
    "\32\7\1\76\11\7\22\0\1\7\1\0\1\7\6\0"+
    "\25\7\1\127\16\7\22\0\1\7\1\0\1\7\6\0"+
    "\31\7\1\130\12\7\22\0\1\7\1\0\1\7\6\0"+
    "\24\7\1\131\17\7\22\0\1\7\1\0\1\7\6\0"+
    "\30\7\1\132\13\7\22\0\1\7\1\0\1\7\6\0"+
    "\31\7\1\133\12\7\22\0\1\7\1\0\1\7\6\0"+
    "\41\7\1\134\2\7\22\0\1\7\1\0\1\7\6\0"+
    "\32\7\1\135\11\7\22\0\1\7\1\0\1\7\6\0"+
    "\33\7\1\136\10\7\22\0\1\7\1\0\1\7\6\0"+
    "\36\7\1\137\5\7\22\0\1\7\1\0\1\7\6\0"+
    "\31\7\1\140\1\141\3\7\1\142\5\7\22\0\1\7"+
    "\1\0\1\7\6\0\32\7\1\143\11\7\22\0\1\7"+
    "\1\0\1\7\71\0\3\144\1\0\1\144\47\0\1\112"+
    "\102\0\1\145\104\0\1\112\107\0\3\146\1\0\1\146"+
    "\66\0\1\147\3\0\3\150\1\0\1\150\66\0\1\105"+
    "\3\0\3\144\1\0\1\144\3\0\1\115\3\0\32\7"+
    "\1\151\11\7\22\0\1\7\1\0\1\7\6\0\17\7"+
    "\1\152\24\7\22\0\1\7\1\0\1\7\6\0\1\153"+
    "\6\7\1\12\34\7\22\0\1\7\1\0\1\7\6\0"+
    "\2\7\1\55\41\7\22\0\1\7\1\0\1\7\6\0"+
    "\5\7\1\122\36\7\22\0\1\7\1\0\1\7\6\0"+
    "\14\7\1\154\27\7\22\0\1\7\1\0\1\7\6\0"+
    "\1\155\43\7\22\0\1\7\1\0\1\7\6\0\36\7"+
    "\1\126\5\7\22\0\1\7\1\0\1\7\6\0\24\7"+
    "\1\156\17\7\22\0\1\7\1\0\1\7\6\0\43\7"+
    "\1\157\22\0\1\7\1\0\1\7\6\0\31\7\1\70"+
    "\12\7\22\0\1\7\1\0\1\7\6\0\33\7\1\126"+
    "\10\7\22\0\1\7\1\0\1\7\6\0\36\7\1\160"+
    "\5\7\22\0\1\7\1\0\1\7\6\0\31\7\1\161"+
    "\12\7\22\0\1\7\1\0\1\7\6\0\36\7\1\162"+
    "\5\7\22\0\1\7\1\0\1\7\6\0\26\7\1\126"+
    "\15\7\22\0\1\7\1\0\1\7\6\0\33\7\1\163"+
    "\10\7\22\0\1\7\1\0\1\7\6\0\23\7\1\164"+
    "\20\7\22\0\1\7\1\0\1\7\6\0\37\7\1\126"+
    "\4\7\22\0\1\7\1\0\1\7\6\0\25\7\1\165"+
    "\16\7\22\0\1\7\1\0\1\7\66\0\1\114\2\0"+
    "\3\144\1\0\1\144\53\0\1\112\115\0\3\150\1\0"+
    "\1\150\7\0\33\7\1\166\10\7\22\0\1\7\1\0"+
    "\1\7\6\0\20\7\1\167\23\7\22\0\1\7\1\0"+
    "\1\7\6\0\1\7\1\55\42\7\22\0\1\7\1\0"+
    "\1\7\6\0\12\7\1\170\31\7\22\0\1\7\1\0"+
    "\1\7\6\0\3\7\1\171\40\7\22\0\1\7\1\0"+
    "\1\7\6\0\34\7\1\172\7\7\22\0\1\7\1\0"+
    "\1\7\6\0\25\7\1\173\16\7\22\0\1\7\1\0"+
    "\1\7\6\0\33\7\1\70\10\7\22\0\1\7\1\0"+
    "\1\7\6\0\42\7\1\126\1\7\22\0\1\7\1\0"+
    "\1\7\6\0\24\7\1\174\17\7\22\0\1\7\1\0"+
    "\1\7\6\0\33\7\1\175\10\7\22\0\1\7\1\0"+
    "\1\7\6\0\24\7\1\176\17\7\22\0\1\7\1\0"+
    "\1\7\6\0\23\7\1\177\20\7\22\0\1\7\1\0"+
    "\1\7\6\0\31\7\1\157\12\7\22\0\1\7\1\0"+
    "\1\7\6\0\21\7\1\200\22\7\22\0\1\7\1\0"+
    "\1\7\6\0\15\7\1\201\26\7\22\0\1\7\1\0"+
    "\1\7\6\0\30\7\1\202\13\7\22\0\1\7\1\0"+
    "\1\7\6\0\25\7\1\202\16\7\22\0\1\7\1\0"+
    "\1\7\6\0\31\7\1\203\12\7\22\0\1\7\1\0"+
    "\1\7\6\0\35\7\1\126\6\7\22\0\1\7\1\0"+
    "\1\7\6\0\25\7\1\204\16\7\22\0\1\7\1\0"+
    "\1\7\6\0\2\7\1\205\41\7\22\0\1\7\1\0"+
    "\1\7\6\0\25\7\1\206\16\7\22\0\1\7\1\0"+
    "\1\7\6\0\43\7\1\207\22\0\1\7\1\0\1\7"+
    "\6\0\23\7\1\210\4\7\1\202\13\7\22\0\1\7"+
    "\1\0\1\7\6\0\32\7\1\127\11\7\22\0\1\7"+
    "\1\0\1\7\6\0\34\7\1\211\7\7\22\0\1\7"+
    "\1\0\1\7\6\0\34\7\1\212\7\7\22\0\1\7"+
    "\1\0\1\7\6\0\23\7\1\213\20\7\22\0\1\7"+
    "\1\0\1\7\6\0\44\7\22\0\1\173\1\0\1\7"+
    "\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6930];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\25\1\11\11\5\1\1\11\1\1\3\11"+
    "\5\1\2\11\22\1\1\0\4\1\1\11\3\0\1\1"+
    "\1\11\24\1\1\0\2\1\1\0\44\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
 
 /* Código personalizado */

	// Se agregó una propiedad para verificar si existen tokens pendientes
	private boolean _existenTokens = false;

	// Contiene las cadenas entre comillas
	StringBuilder string = new StringBuilder();

	public boolean existenTokens(){
		return this._existenTokens;
	}

	public int getLine() {
		return yyline;
	}

	public int getColumn() {
		return yycolumn;
	}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexicoFase2(java.io.Reader in) {
   	/* Código que se ejecutará en el constructor de la clase */
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 226) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
     
 /* Código a ejecutar al finalizar el análisis, en este caso cambiaremos el valor de una variable bandera */
 this._existenTokens = false;
 
  yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token next_token() throws java.io.IOException, Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new Token( sym.EOF, yycolumn, yyline+1, -1, yytext(), "FIN" );
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //throw new Exception();
            }
          case 32: break;
          case 2: 
            { Token t = new Token( sym.IDENTIFICADOR, yycolumn, yyline+1, 0, yytext(), Token.STR_IDENT );
		this._existenTokens = true;
		return t;
            }
          case 33: break;
          case 3: 
            { Token t = new Token( sym.STEP, yycolumn, yyline+1, 0, yytext(), Token.STEP );
		this._existenTokens = true;
		return t;
            }
          case 34: break;
          case 4: 
            { Token t = new Token( 0, yycolumn, yyline+1, 0, yytext(), "SIMBOLO");
		this._existenTokens = true;
		return t;
            }
          case 35: break;
          case 5: 
            { Token t = new Token( sym.PUNTO, yycolumn, yyline+1, -1, yytext(), Token.CARACTER );
		this._existenTokens = true;
		return t;
            }
          case 36: break;
          case 6: 
            { Token t = new Token( sym.COMA, yycolumn, yyline+1, -1, yytext(), Token.CARACTER );
		this._existenTokens = true;
		return t;
            }
          case 37: break;
          case 7: 
            { Token t = new Token( sym.PUNTO_Y_COMA, yycolumn, yyline+1, -1, yytext(), Token.CARACTER );
		this._existenTokens = true;
		return t;
            }
          case 38: break;
          case 8: 
            { Token t = new Token( sym.IGUAL_SIMPLE, yycolumn, yyline+1, -1, yytext(), Token.SIMBOLO );
		this._existenTokens = true;
		return t;
            }
          case 39: break;
          case 9: 
            { Token t = new Token( sym.LPAREN, yycolumn, yyline+1, -1, yytext(), Token.CARACTER );
		this._existenTokens = true;
		return t;
            }
          case 40: break;
          case 10: 
            { Token t = new Token( sym.RPAREN, yycolumn, yyline+1, -1, yytext(), Token.CARACTER );
		this._existenTokens = true;
		return t;
            }
          case 41: break;
          case 11: 
            { string.setLength(0);
			yybegin( CADENA );
            }
          case 42: break;
          case 12: 
            { Token t = new Token( sym.OPERADOR_ARIT, yycolumn, yyline+1, 0, yytext(), Token.OPERADOR_ARIT );
		this._existenTokens = true;
		return t;
            }
          case 43: break;
          case 13: 
            { Token t = new Token( sym.NUMERO_ENTERO, yycolumn, yyline+1, 0, yytext(), Token.TIPO );
		this._existenTokens = true;
		return t;
            }
          case 44: break;
          case 14: 
            { // Quizás este token no proceda y simplemente haya que limpiar los saltos
	//Token t = new Token( 0, yycolumn, yyline+1, 0, "Enter", "NUEVA_LINEA");
	//this._existenTokens = true;
	//return t;
            }
          case 45: break;
          case 15: 
            { // Ignorar cuando se ingrese un espacio
	//Token t = new Token( 0, yycolumn, yyline+1, 0, "Espacio", "ESPACIO");
	//this._existenTokens = true;
	//return t;
            }
          case 46: break;
          case 16: 
            { string.append( yytext() );
            }
          case 47: break;
          case 17: 
            { Token t = new Token( sym.CADENA, yycolumn, yyline+1, -1, string.toString(), Token.STRING );
				this._existenTokens = true;
				yybegin( YYINITIAL );
				return t;
            }
          case 48: break;
          case 18: 
            { Token t = new Token( sym.PALABRA_RESERVADA, yycolumn, yyline+1, -1, yytext(), Token.PALABRA_RESERVADA );
		this._existenTokens = true;
		return t;
            }
          case 49: break;
          case 19: 
            { Token t = new Token( sym.CLEF_VALUE, yycolumn, yyline+1, 0, yytext(), Token.SIMBOLO );
		this._existenTokens = true;
		return t;
            }
          case 50: break;
          case 20: 
            { Token t = new Token( sym.ACCENT_VALUE, yycolumn, yyline+1, 0, yytext(), Token.SIMBOLO );
		this._existenTokens = true;
		return t;
            }
          case 51: break;
          case 21: 
            { Token t = new Token( sym.VARIABLE, yycolumn, yyline+1, 0, yytext(), Token.VARIABLE );
		this._existenTokens = true;
		return t;
            }
          case 52: break;
          case 22: 
            { Token t = new Token( sym.OPERADOR_NOTA, yycolumn, yyline+1, 0, yytext(), Token.OPERADOR_NOTA);
		this._existenTokens = true;
		return t;
            }
          case 53: break;
          case 23: 
            { string.append( "\"" );
            }
          case 54: break;
          case 24: 
            { Token t = new Token( sym.END, yycolumn, yyline+1, -1, yytext(), Token.PALABRA_RESERVADA );
		this._existenTokens = true;
		return t;
            }
          case 55: break;
          case 25: 
            { Token t = new Token( sym.TIPO, yycolumn, yyline+1, 0, yytext(), Token.TIPO);
		this._existenTokens = true;
		return t;
            }
          case 56: break;
          case 26: 
            { Token t = new Token( sym.NUMERO_REAL, yycolumn, yyline+1, 0, yytext(), Token.TIPO );
		this._existenTokens = true;
		return t;
            }
          case 57: break;
          case 27: 
            { Token t = new Token( sym.NUMERO_INT_FRAC, yycolumn, yyline+1, 0, yytext(), Token.TIPO );
		this._existenTokens = true;
		return t;
            }
          case 58: break;
          case 28: 
            { Token t = new Token( sym.BEGIN, yycolumn, yyline+1, -1, yytext(), Token.PALABRA_RESERVADA );
		this._existenTokens = true;
		return t;
            }
          case 59: break;
          case 29: 
            { Token t = new Token( sym.TRANS, yycolumn, yyline+1, 0, yytext(), Token.SIMBOLO );
		this._existenTokens = true;
		return t;
            }
          case 60: break;
          case 30: 
            { Token t = new Token( sym.IMPORT, yycolumn, yyline+1, -1, yytext(), Token.PALABRA_RESERVADA );
		this._existenTokens = true;
		return t;
            }
          case 61: break;
          case 31: 
            { Token t = new Token( sym.PACKAGE, yycolumn, yyline+1, -1, yytext(), Token.PALABRA_RESERVADA );
		this._existenTokens = true;
		return t;
            }
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
